services:
    tagcade.worker.workers.execute_integration_job_worker:
        class: Tagcade\Worker\Workers\ExecuteIntegrationJobWorker
        arguments:
            - '@tagcade.service.integration.integration_manager'
