services:
    tagcade.worker.workers.execute_integration_job_worker:
        class: Tagcade\Worker\Workers\ExecuteIntegrationJobWorker
        arguments:
            - '@monolog.logger'
            - '%integration_log_file_dir%'
            - '%integration_temp_file_dir%'
