services:
    redis.app_cache:
        class: Redis
        calls:
            - [connect, ["%redis_app_cache_host%","%redis_app_cache_port%"]]

    tagcade.service.lock.red_lock:
        class: Tagcade\Service\Lock\RedLock
        arguments:
            - ['@redis.app_cache']

    tagcade.service.lock.lock_service:
        class: Tagcade\Service\Lock\LockService
        arguments:
            - '@tagcade.service.lock.red_lock'
            - '%lock_key_prefix%'
            - '%lock_key_ttl%'

    tagcade.worker.workers.execute_integration_job_worker:
        class: Tagcade\Worker\Workers\ExecuteIntegrationJobWorker
        arguments:
            - '@monolog.logger'
            - '@tagcade.service.lock.lock_service'
            - '@tagcade.service.integration.integration_manager'
            - '%retry_when_fail_max_retries_number%'
            - '%retry_when_fail_delay_before_retry%'
            - '@tagcade_app.rest_client'

    tagcade.service.integration.integrations.redshift_video.redshift_pdo:
        class: Tagcade\Service\Integration\Integrations\RedshiftVideo\RedShiftPDO
        arguments:
            - '%redshift_db_type%'
            - '%redshift_db_name%'
            - '%redshift_db_host%'
            - '%redshift_db_port%'
            - '%redshift_db_username%'
            - '%redshift_db_password%'
