services:
    tagcade.worker.workers.get_partner_report_worker:
        class: Tagcade\Worker\Workers\GetPartnerReportWorker
        arguments:
            - '@tagcade.service.integration.integration_manager'
