services:
    tagcade.service.fetcher.fetchers.across33:
        class: Tagcade\Service\Fetcher\Fetchers\Across33\Across33Fetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.across33:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Across33\Across33
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.across33'
