services:
    tagcade.service.fetcher.fetchers.ads4games:
        class: Tagcade\Service\Fetcher\Fetchers\Ads4Games\Ads4GamesFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.ads4games:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Ads4Games\Ads4Games
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.ads4games'