services:
    tagcade.service.fetcher.fetchers.adtech:
        class: Tagcade\Service\Fetcher\Fetchers\Adtech\AdtechFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.adtech:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Adtech\Adtech
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.adtech'