services:
    tagcade.service.integration.integrations.aws.s3:
        class: Tagcade\Service\Integration\Integrations\AWS\AwsS3
        arguments:
            - '@logger'
            - '@tagcade.service.file_storage_service'
            - '@tagcade_app.rest_client'