services:
    tagcade.service.fetcher.fetchers.conversant:
        class: Tagcade\Service\Fetcher\Fetchers\Conversant\ConversantFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.conversant:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Conversant\Conversant
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.conversant'

