services:
    tagcade.service.fetcher.fetchers.cpmbase:
        class: Tagcade\Service\Fetcher\Fetchers\CpmBase\CpmBaseFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.cpmbase:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\CpmBase\CpmBase
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.cpmbase'