services:
    tagcade.command.cpmbase.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\CpmBase\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.cpmbase:
        class: Tagcade\DataSource\CpmBase\CpmBaseFetcher
        calls:
            - [setLogger, [@logger]]
            - [setDownloadFileHelper, [@tagcade.data_source.fetcher.helper]]