services:
    tagcade.service.fetcher.fetchers.defymedia:
        class: Tagcade\Service\Fetcher\Fetchers\DefyMedia\DefyMediaFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.defy_media:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\DefyMedia\DefyMedia
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.defymedia'