services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.defy_media.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\DefyMedia\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.defy_media:
        class: Tagcade\DataSource\DefyMedia\DefyMediaFetcher
        calls:
            - [setLogger, [@logger]]