services:
    tagcade.service.fetcher.fetchers.districtm:
        class: Tagcade\Service\Fetcher\Fetchers\Districtm\DistrictmFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.districtm:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Districtm\Districtm
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.districtm'

