services:
    tagcade.service.fetcher.fetchers.epom:
        class: Tagcade\Service\Fetcher\Fetchers\Epom\EpomMarketFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.epom_market:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Epom\Epom
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.epom'