services:
    tagcade.service.fetcher.fetchers.gamut:
        class: Tagcade\Service\Fetcher\Fetchers\Gamut\GamutFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.gamut:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Gamut\Gamut
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.gamut'
