services:
    tagcade.service.fetcher.fetchers.komoona:
        class: Tagcade\Service\Fetcher\Fetchers\Komoona\KomoonaFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.komoona:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Komoona\Komoona
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.komoona'