services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.media.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\Media\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.media:
        class: Tagcade\DataSource\Media\MediaFetcher
        calls:
            - [setLogger, [@logger]]
            - [setDownloadFileHelper, [@tagcade.data_source.fetcher.helper]]