services:
    tagcade.service.fetcher.fetchers.media:
        class: Tagcade\Service\Fetcher\Fetchers\Media\MediaNetFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.media_net:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Media\Media
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.media'