services:
    tagcade.service.fetcher.fetchers.nativeads:
        class: Tagcade\Service\Fetcher\Fetchers\NativeAds\NativeAdsFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.nativeads:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\NativeAds\NativeAds
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.nativeads'