services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.nativeads.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\NativeAds\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.nativeads:
        class: Tagcade\DataSource\NativeAds\NativeAdsFetcher
        calls:
            - [setLogger, [@logger]]
            - [setDownloadFileHelper, [@tagcade.data_source.fetcher.helper]]