services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.openx.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\Openx\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.openx:
        class: Tagcade\DataSource\Openx\OpenxFetcher
        calls:
            - [setLogger, [@logger]]
            - [setDownloadFileHelper,[@tagcade.data_source.fetcher.helper]]

