services:
    tagcade.service.fetcher.fetchers.pubventures:
        class: Tagcade\Service\Fetcher\Fetchers\PubVentures\PubVenturesFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.pub_ventures:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\PubVentures\PubVentures
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.pubventures'