services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.pub_ventures.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\PubVentures\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.pub_ventures:
        class: Tagcade\DataSource\PubVentures\PubVenturesFetcher
        calls:
            - [setLogger, [@logger]]
            - [setDownloadFileHelper, [@tagcade.data_source.fetcher.helper]]