services:
    tagcade.service.fetcher.fetchers.pulsepoint:
        class: Tagcade\Service\Fetcher\Fetchers\PulsePoint\PulsePointFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.pulse_point:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\PulsePoint\PulsePoint
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.pulsepoint'