services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]


    tagcade.data_source.pulsepoint.task_factory:
        class: Tagcade\DataSource\PulsePoint\TaskFactory
        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.pp.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\PulsePoint\GetAccountDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.pulse_point:
        class: Tagcade\DataSource\PulsePoint\PulsePointFetcher
