services:
    tagcade.service.integration.integrations.redshift_video.redshiftaggregatedvideo:
        class: Tagcade\Service\Integration\Integrations\RedshiftVideo\RedshiftAggregatedVideo\RedshiftAggregatedVideo
        arguments:
            - '@logger'
            - '@tagcade.service.download_file_helper'
            - '@tagcade.service.file_storage_service'
            - '@tagcade_app.rest_client'
            - '@redis.app_cache'
            - '@tagcade.service.integration.integrations.redshift_video.redshift_pdo'
