services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.sovrn.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\Sovrn\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.sovrn:
        class: Tagcade\DataSource\Sovrn\SovrnFetcher
