services:
    tagcade.service.fetcher.fetchers.sovrn:
        class: Tagcade\Service\Fetcher\Fetchers\Sovrn\SovrnFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.sovrn:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Sovrn\Sovrn
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.sovrn'