services:
    tagcade.service.integration.integrations.demand_partner.taboolaapi:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\TaboolaApi\TaboolaApi
        arguments:
            - '@logger'
            - '@tagcade.service.download_file_helper'
            - '@tagcade.service.file_storage_service'
            - '@tagcade_app.rest_client'
            - '@curl'
