services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.technorati.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\Technorati\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.technorati:
        class: Tagcade\DataSource\Technorati\TechnoratiFetcher
        calls:
            - [setLogger, [@logger]]
            - [setDownloadFileHelper,[@tagcade.data_source.fetcher.helper]]

