services:
    tagcade.service.fetcher.fetchers.technorati:
        class: Tagcade\Service\Fetcher\Fetchers\Technorati\TechnoratiFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.technorati:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\Technorati\Technorati
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.technorati'

