services:
    tagcade.service.fetcher.fetchers.yellowhammer:
        class: Tagcade\Service\Fetcher\Fetchers\YellowHammer\YellowHammerFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.demand_partner.yellow_hammer:
        class: Tagcade\Service\Integration\Integrations\DemandPartner\YellowHammer\YellowHammer
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.yellowhammer'