services:
#    tagcade.data_source.koomona.task_factory:
#        class: Tagcade\DataSource\PulsePoint\TaskFactory
#        arguments: [@tagcade.web_driver_factory, @logger]

    tagcade.command.yellow_hammer.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\YellowHammer\GetDataCommand
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.yellow_hammer:
        class: Tagcade\DataSource\YellowHammer\YellowHammerFetcher
        calls:
            - [setLogger, [@logger]]