services:
    tagcade.service.fetcher.ui.conversant:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\Conversant\ConversantFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.conversant
        calls:
            - [setIntegrationCName,[%integration_cname_conversant%]]

