services:
    tagcade.service.fetcher.ui.cpmbase:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\CpmBase\CpmBaseFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.cpmbase