services:
    tagcade.service.fetcher.ui.defy_media:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\DefyMedia\DefyMediaFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.defy_media