services:
    tagcade.service.fetcher.ui.districtm:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\Districtm\DistrictmFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.districtm
