services:
    tagcade.service.fetcher.ui.epom_market:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\Epom\EpomMarketFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.epom_market
        calls:
            - [setIntegrationCName,[%integration_cname_epom-market%]]