services:
    tagcade.service.fetcher.ui.media_net:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\Media\MediaNetFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.media_net