services:
    tagcade.service.fetcher.ui.pub_ventures:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\PubVentures\PubVenturesFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.pub_ventures
        calls:
            - [setIntegrationCName,[%integration_cname_pub-ventures%]]