services:
    tagcade.service.fetcher.ui.pulse_point:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\PulsePoint\PulsePointFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.pulse_point