services:
    tagcade.service.fetcher.ui.technorati:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\Technorati\TechnoratiFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.technorati