services:
    tagcade.service.fetcher.ui.yellow_hammer:
        class: Tagcade\Service\Fetcher\Fetchers\Ui\YellowHammer\YellowHammerFetcher
        parent: tagcade.service.fetcher.ui.abstract_ui_fetcher
        arguments:
            - @tagcade.data_source.fetcher.yellow_hammer