services:
    tagcade.service.fetcher.api_fetcher:
        class: Tagcade\Service\Fetcher\Fetchers\ApiFetcher
        arguments:
            - @logger
            -
                - @tagcade.service.fetcher.api.tagcade

