services:
    tagcade.service.fetcher.ui_fetcher:
        class: Tagcade\Service\Fetcher\Fetchers\UiFetcher
        arguments:
            - @logger
            -
                - @tagcade.service.fetcher.ui.across33

