services:
    tagcade.service.fetcher.fetchers.ui_fetcher:
        class: Tagcade\Service\Fetcher\Fetchers\UiFetcher
        arguments:
            - @logger
            -
                - @tagcade.service.fetcher.ui.across33
                - @tagcade.service.fetcher.ui.ads4games
                - @tagcade.service.fetcher.ui.adtech
                - @tagcade.service.fetcher.ui.conversant
                - @tagcade.service.fetcher.ui.cpmbase
                - @tagcade.service.fetcher.ui.defy_media
                - @tagcade.service.fetcher.ui.districtm
                - @tagcade.service.fetcher.ui.epom_market
                - @tagcade.service.fetcher.ui.komoona
                - @tagcade.service.fetcher.ui.media_net
                - @tagcade.service.fetcher.ui.nativeads
                - @tagcade.service.fetcher.ui.openx
                - @tagcade.service.fetcher.ui.pub_ventures
                - @tagcade.service.fetcher.ui.pulse_point
                - @tagcade.service.fetcher.ui.sovrn
                - @tagcade.service.fetcher.ui.technorati
                - @tagcade.service.fetcher.ui.yellow_hammer

