services:
    tagcade.service.fetcher.api.abstract_api_fetcher:
        class: Tagcade\Service\Fetcher\Fetchers\Api\AbstractApiFetcher
        abstract: true
        arguments:
            -%tagcade.default_data_path%
            -@logger
