services:
    tagcade.service.fetcher.fetchers.cedato_external:
        class: Tagcade\Service\Fetcher\Fetchers\CedatoExternal\CedatoExternalFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.video.cedato_external:
        class: Tagcade\Service\Integration\Integrations\Video\CedatoExternal\CedatoExternal
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.cedato_external'
