services:
    tagcade.service.fetcher.fetchers.optimaticinternaldemand:
        class: Tagcade\Service\Fetcher\Fetchers\OptimaticInternalDemand\OptimaticInternalDemandFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.video.optimaticinternaldemand:
        class: Tagcade\Service\Integration\Integrations\Video\OptimaticInternalDemand\OptimaticInternalDemand
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.optimaticinternaldemand'
