services:
    tagcade.service.fetcher.fetchers.optimaticinternalsupply:
        class: Tagcade\Service\Fetcher\Fetchers\OptimaticInternalSupply\OptimaticInternalSupplyFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.video.optimaticinternalsupply:
        class: Tagcade\Service\Integration\Integrations\Video\OptimaticInternalSupply\OptimaticInternalSupply
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.optimaticinternalsupply'
