services:
    tagcade.service.fetcher.fetchers.optimaticinternalmarketplace:
        class: Tagcade\Service\Fetcher\Fetchers\OptimaticInternalMarketplace\OptimaticInternalMarketplaceFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.video.optimaticinternalmarketplace:
        class: Tagcade\Service\Integration\Integrations\Video\OptimaticInternalMarketplace\OptimaticInternalMarketplace
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.optimaticinternalmarketplace'
