services:
    tagcade.service.integration.integrations.video.springserveapi:
        class: Tagcade\Service\Integration\Integrations\Video\SpringServeApi\SpringServeApi
        arguments:
            - '@logger'
            - '@tagcade.service.download_file_helper'
            - '@tagcade.service.file_storage_service'
            - '@tagcade_app.rest_client'
            - '@curl'
