services:
    tagcade.service.fetcher.fetchers.streamrail_external:
        class: Tagcade\Service\Fetcher\Fetchers\StreamRailExternal\StreamRailExternalFetcher
        parent: tagcade.service.fetcher.fetchers.partner_fetcher_abstract

    tagcade.service.integration.integrations.video.streamrail_external:
        class: Tagcade\Service\Integration\Integrations\Video\StreamRailExternal\StreamRailExternal
        parent: tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract
        arguments:
            - '@tagcade.service.integration.integrations.web_driver_service'
            - '@tagcade.service.fetcher.fetchers.streamrail_external'
