services:
    yaml:
        class: Symfony\Component\Yaml\Yaml

    tagcade.command.pulsepoint.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\PulsePoint\GetDataCommand
        arguments: [%tagcade.default_data_path%, "@yaml", "@logger"]
        tags:
            -  { name: console.command }

    tagcade.command.admeta.get_data_command:
        class: Tagcade\Bundle\AppBundle\Command\AdMeta\GetDataCommand
        arguments: [%tagcade.default_data_path%, "@yaml", "@logger"]
        tags:
            -  { name: console.command }
