imports:
    - { resource: services/komoona.yml }
    - { resource: services/yellow.hammer.yml }
    - { resource: services/defy.media.yml }
    - { resource: services/across33.yml }
    - { resource: services/sovrn.yml }
    - { resource: services/pulse.point.yml }
    - { resource: services/media.net.yml }
    - { resource: services/cpmbase.yml }
    - { resource: services/nativeads.yml }
    - { resource: services/ads4games.yml }
    - { resource: services/adtech.yml }
    - { resource: services/epom.market.yml }
    - { resource: services/pub.ventures.yml }
    - { resource: services/districtm.yml }
    - { resource: services/conversant.yml }
    - { resource: services/openx.yml }
    - { resource: services/technorati.yml }
    - { resource: services/Fetcher/ui-fetcher.yml }
    - { resource: services/Fetcher/Ui/abstract-ui-fetcher.yml }
    - { resource: services/Fetcher/Ui/across33.yml }
    - { resource: services/Fetcher/Ui/ads4games.yml }
    - { resource: services/Fetcher/Ui/adtech.yml }
    - { resource: services/Fetcher/Ui/conversant.yml }
    - { resource: services/Fetcher/Ui/cpmbase.yml }
    - { resource: services/Fetcher/Ui/defy.media.yml }
    - { resource: services/Fetcher/Ui/districtm.yml }
    - { resource: services/Fetcher/Ui/epom.market.yml }
    - { resource: services/Fetcher/Ui/komoona.yml }
    - { resource: services/Fetcher/Ui/media.net.yml }
    - { resource: services/Fetcher/Ui/nativeads.yml }
    - { resource: services/Fetcher/Ui/openx.yml }
    - { resource: services/Fetcher/Ui/pub.ventures.yml }
    - { resource: services/Fetcher/Ui/pulse.point.yml }
    - { resource: services/Fetcher/Ui/sovrn.yml }
    - { resource: services/Fetcher/Ui/technorati.yml }
    - { resource: services/Fetcher/Ui/yellow.hammer.yml }
    - { resource: services/Fetcher/api-fetcher.yml }
    - { resource: services/Fetcher/Api/abstract-api-fetcher.yml }
    - { resource: services/Fetcher/Api/tagcade.yml }

services:
    yaml:
        class: Symfony\Component\Yaml\Yaml

    tagcade.web_driver_factory:
        class: Tagcade\WebDriverFactory
        arguments:
            - %selenium_server_url%
            - @logger
    curl:
        class: anlutro\cURL\cURL
        scope: prototype

    tagcade.data_source.admeta.api:
        class: Tagcade\DataSource\AdMeta\Api
        arguments: [@curl, @logger]
        scope: prototype

    tagcade.command.admeta.get_data:
        class: Tagcade\Bundle\AppBundle\Command\AdMeta\GetDataCommand
        # notice the = sign at the end of the admeta api service, this disables strict checking
        # this is because we use a different scope
        arguments: [@tagcade.data_source.admeta.api=, %tagcade.default_data_path%, @yaml, @logger]
        tags:
            -  { name: console.command }

    tagcade.command.get_all_partner_data:
        class: Tagcade\Bundle\AppBundle\Command\GetAllPartnersDataCommand
        arguments:
            - %partners%
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.helper:
        class: Tagcade\Service\DownloadFileHelper
        arguments:
            - %tagcade.default_data_path%
            - %tagcade_download_time_out%
            - @logger
            - %kernel.root_dir%

    ### rest client
    rest.client:
        class: RestClient\CurlRestClient
        public: false

    tagcade_app.rest_client:
        class: Tagcade\Service\Core\TagcadeRestClient
        arguments:
            - @rest.client
            - %tagcade_user_name%
            - %tagcade_user_password%
            - %tagcade_get_token_url%
            - %tagcade_get_list_publisher_url%
            - %ur_get_list_integrations_to_be_executed_url%
            - %ur_update_last_execution_time_for_integration_url%
        calls:
            - [setLogger, [@logger]]

    tagcade.service.integration_activator:
        class: Tagcade\Service\Integration\IntegrationActivator
        arguments:
            - @tagcade_app.rest_client
            - @leezy.pheanstalk.primary
            - %fetcher_worker_tube%
            - %pheanstalk_ttr%
