imports:
    - { resource: services/aws.yml }
    - { resource: services/across33.yml }
    - { resource: services/admeta.yml }
    - { resource: services/ads4games.yml }
    - { resource: services/adtech.yml }
    - { resource: services/conversant.yml }
    - { resource: services/cpmbase.yml }
    - { resource: services/defy.media.yml }
    - { resource: services/districtm.yml }
    - { resource: services/epom.market.yml }
    - { resource: services/gamut.yml }
    - { resource: services/komoona.yml }
    - { resource: services/media.net.yml }
    - { resource: services/nativeads.yml }
    - { resource: services/openx.yml }
    - { resource: services/pub.ventures.yml }
    - { resource: services/pubvantage.yml }
    - { resource: services/pulse.point.yml }
    - { resource: services/sovrn.yml }
    - { resource: services/technorati.yml }
    - { resource: services/yellow.hammer.yml }
    - { resource: services/video/lkqd.yml }
    - { resource: services/video/springserve.yml }
    - { resource: services/video/cedato.yml }
    - { resource: services/video/streamrail.yml }
    - { resource: services/general/basic_api.yml }
    - { resource: services/video/vertainternal.yml }
    - { resource: services/video/vertaexternal.yml }
    - { resource: services/video/optimaticinternalmarketplace.yml }
    - { resource: services/video/optimaticinternaldemand.yml }
    - { resource: services/video/optimaticexternal.yml }
    - { resource: services/video/optimaticinternalsupply.yml }
    - { resource: services/connatix.yml }
    - { resource: services/mediadotnetapi.yml }


services:
    yaml:
        class: Symfony\Component\Yaml\Yaml

    tagcade.web_driver_factory:
        class: Tagcade\WebDriverFactory
        arguments:
            - %selenium_server_url%
            - '@logger'
            - %chrome_folder_path%
    curl:
        class: anlutro\cURL\cURL

    tagcade.service.integration.integrations.web_driver_service:
        class: Tagcade\Service\WebDriverService
        arguments:
            - '@logger'
            - '@tagcade.web_driver_factory'
            - '@tagcade_app.rest_client'
            - '%kernel.root_dir%'
            - '%tagcade.default_data_path%'
            - '%chrome_folder_path%'
            - '@tagcade.service.integration.delete_file_service'
            - '@tagcade_app.rest_client'
            - '%remove_chrome_folder_path_interval%'
            - '@tagcade.service.download_file_helper'

    tagcade.service.download_file_helper:
        class: Tagcade\Service\DownloadFileHelper
        arguments:
            - '%tagcade.default_data_path%'
            - '@logger'
            - '%kernel.root_dir%'
            - '@tagcade.service.integration.delete_file_service'

    tagcade.service.integration.delete_file_service:
        class: Tagcade\Service\DeleteFileService
        arguments:
            - '@logger'

    ### rest client
    rest.client:
        class: RestClient\CurlRestClient
        public: false

    tagcade_app.rest_client:
        class: Tagcade\Service\Core\TagcadeRestClient
        arguments:
            - '@rest.client'
            - '%tagcade_user_name%'
            - '%tagcade_user_password%'
            - '%tagcade_get_token_url%'
            - '%tagcade_get_list_publisher_url%'
            - '%ur_get_list_integrations_to_be_executed_url%'
            - '%ur_get_list_integrations_by_datasource_url%'
            - '%ur_create_alert_url%'
            - '%ur_update_integration_schedule_pending_url%'
            - '%ur_update_integration_schedule_finishorfail_url%'
            - '%ur_update_backfill_history_url%'
            - '%ur_update_backfill_missing_dates_url%'

        calls:
            - [setLogger, ['@logger']]

    tagcade.service.integration_activator:
        class: Tagcade\Service\Integration\IntegrationActivator
        arguments:
            - '@tagcade_app.rest_client'
            - '@leezy.pheanstalk.primary'
            - '%fetcher_worker_tube%'
            - '%pheanstalk_ttr%'

    tagcade.service.file_storage_service:
        class: Tagcade\Service\FileStorageService
        arguments:
            - '%tagcade.default_data_path%'
            - '%kernel.root_dir%'

    tagcade.service.tagcade_api_service:
        class: Tagcade\Service\TagcadeApiService

    tagcade.service.ur_api_service:
        class: Tagcade\Service\URApiService
        arguments:
            - '%ur_post_datasource_import_json_data%'
            - '@logger'

    tagcade.service.fetcher.fetchers.partner_fetcher_abstract:
        class: Tagcade\Service\Fetcher\PartnerFetcherAbstract
        abstract: true
        arguments:
            - '@logger'
            - '@tagcade.service.download_file_helper'
            - '@tagcade_app.rest_client'

    tagcade.service.integration.integrations.demand_partner.integration_web_driver_abstract:
        class: Tagcade\Service\Integration\Integrations\IntegrationWebDriverAbstract
        abstract: true

    tagcade.service.integration.integrations.demand_partner.integration_demand_partner_abstract:
        class: Tagcade\Service\Integration\Integrations\IntegrationDemandPartnerAbstract
        abstract: true

    tagcade.service.integration.integrations.video_demand_partner.integration_video_demand_partner_abstract:
        class: Tagcade\Service\Integration\Integrations\IntegrationVideoDemandPartnerAbstract
        abstract: true
#        arguments:
#            - '@tagcade.service.integration.integrations.web_driver_service'

    tagcade.service.integration.integration_manager:
        class: Tagcade\Service\Integration\IntegrationManager
        arguments:
            -
                - '@tagcade.service.integration.integrations.aws.s3'
                - '@tagcade.service.integration.integrations.general.basic_api'
                - '@tagcade.service.integration.integrations.pubvantage.account_report'
                - '@tagcade.service.integration.integrations.demand_partner.across33'
                - '@tagcade.service.integration.integrations.demand_partner.admeta'
                - '@tagcade.service.integration.integrations.demand_partner.ads4games'
                - '@tagcade.service.integration.integrations.demand_partner.adtech'
                - '@tagcade.service.integration.integrations.demand_partner.conversant'
                - '@tagcade.service.integration.integrations.demand_partner.cpmbase'
                - '@tagcade.service.integration.integrations.demand_partner.defy_media'
                - '@tagcade.service.integration.integrations.demand_partner.districtm'
                - '@tagcade.service.integration.integrations.demand_partner.epom_market'
                - '@tagcade.service.integration.integrations.demand_partner.gamut'
                - '@tagcade.service.integration.integrations.demand_partner.komoona'
                - '@tagcade.service.integration.integrations.demand_partner.media_net'
                - '@tagcade.service.integration.integrations.demand_partner.nativeads'
                - '@tagcade.service.integration.integrations.demand_partner.openx'
                - '@tagcade.service.integration.integrations.demand_partner.pub_ventures'
                - '@tagcade.service.integration.integrations.demand_partner.pulse_point'
                - '@tagcade.service.integration.integrations.demand_partner.sovrn'
                - '@tagcade.service.integration.integrations.demand_partner.technorati'
                - '@tagcade.service.integration.integrations.demand_partner.yellow_hammer'
                - '@tagcade.service.integration.integrations.demand_partner.connatix'
                - '@tagcade.service.integration.integrations.demand_partner.mediadotnetapi'
                - '@tagcade.service.integration.integrations.video.lkqd'
                - '@tagcade.service.integration.integrations.video.springserve'
                - '@tagcade.service.integration.integrations.video.cedato'
                - '@tagcade.service.integration.integrations.video.streamrail'
                - '@tagcade.service.integration.integrations.video.verta_internal'
                - '@tagcade.service.integration.integrations.video.verta_external'
                - '@tagcade.service.integration.integrations.video.optimaticinternalmarketplace'
                - '@tagcade.service.integration.integrations.video.optimaticinternaldemand'
                - '@tagcade.service.integration.integrations.video.optimaticexternal'
                - '@tagcade.service.integration.integrations.video.optimaticinternalsupply'
