imports:
    - { resource: services/komoona.yml }
    - { resource: services/yellow.hammer.yml }
    - { resource: services/defy.media.yml }
    - { resource: services/across33.yml }
    - { resource: services/sovrn.yml }
    - { resource: services/pulse.point.yml }
    - { resource: services/media.yml }
    - { resource: services/cpmbase.yml }
    - { resource: services/nativeads.yml }
    - { resource: services/ads4games.yml }
    - { resource: services/adtech.yml }
    - { resource: services/epom.market.yml }
    - { resource: services/pub.ventures.yml }
    - { resource: services/districtm.yml }
    - { resource: services/conversant.yml }
    - { resource: services/openx.yml }

services:
    yaml:
        class: Symfony\Component\Yaml\Yaml

    tagcade.web_driver_factory:
        class: Tagcade\WebDriverFactory
        arguments:
            - %selenium_server_url%
            - @logger
    curl:
        class: anlutro\cURL\cURL
        scope: prototype

    tagcade.data_source.admeta.api:
        class: Tagcade\DataSource\AdMeta\Api
        arguments: [@curl, @logger]
        scope: prototype

    tagcade.command.admeta.get_data:
        class: Tagcade\Bundle\AppBundle\Command\AdMeta\GetDataCommand
        # notice the = sign at the end of the admeta api service, this disables strict checking
        # this is because we use a different scope
        arguments: [@tagcade.data_source.admeta.api=, %tagcade.default_data_path%, @yaml, @logger]
        tags:
            -  { name: console.command }

    tagcade.command.get_all_partner_data:
        class: Tagcade\Bundle\AppBundle\Command\GetAllPartnersDataCommand
        arguments:
            - %partners%
        tags:
            -  { name: console.command }

    tagcade.data_source.fetcher.helper:
        class: Tagcade\Service\DownloadFileHelper
        arguments:
            - %tagcade.default_data_path%
            - %tagcade_download_time_out%
            - @logger

    ### rest client
    rest.client:
        class: RestClient\CurlRestClient
        public: false

    tagcade_app.rest_client:
        class: Tagcade\Service\Core\TagcadeRestClient
        arguments:
            - @rest.client
            - %tagcade_user_name%
            - %tagcade_user_password%
            - %tagcade_get_token_url%
            - %tagcade_get_list_publisher_url%
        calls:
            - [setLogger, [@logger]]

